// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jclarity.had_one_dismissal.domain;

import com.jclarity.had_one_dismissal.domain.Seeker;
import com.jclarity.had_one_dismissal.domain.SeekerDataOnDemand;
import com.jclarity.had_one_dismissal.domain.SeekerIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SeekerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SeekerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SeekerIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SeekerIntegrationTest: @Transactional;
    
    @Autowired
    SeekerDataOnDemand SeekerIntegrationTest.dod;
    
    @Test
    public void SeekerIntegrationTest.testCountSeekers() {
        Assert.assertNotNull("Data on demand for 'Seeker' failed to initialize correctly", dod.getRandomSeeker());
        long count = Seeker.countSeekers();
        Assert.assertTrue("Counter for 'Seeker' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SeekerIntegrationTest.testFindSeeker() {
        Seeker obj = dod.getRandomSeeker();
        Assert.assertNotNull("Data on demand for 'Seeker' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Seeker' failed to provide an identifier", id);
        obj = Seeker.findSeeker(id);
        Assert.assertNotNull("Find method for 'Seeker' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Seeker' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SeekerIntegrationTest.testFindAllSeekers() {
        Assert.assertNotNull("Data on demand for 'Seeker' failed to initialize correctly", dod.getRandomSeeker());
        long count = Seeker.countSeekers();
        Assert.assertTrue("Too expensive to perform a find all test for 'Seeker', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Seeker> result = Seeker.findAllSeekers();
        Assert.assertNotNull("Find all method for 'Seeker' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Seeker' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SeekerIntegrationTest.testFindSeekerEntries() {
        Assert.assertNotNull("Data on demand for 'Seeker' failed to initialize correctly", dod.getRandomSeeker());
        long count = Seeker.countSeekers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Seeker> result = Seeker.findSeekerEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Seeker' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Seeker' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SeekerIntegrationTest.testFlush() {
        Seeker obj = dod.getRandomSeeker();
        Assert.assertNotNull("Data on demand for 'Seeker' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Seeker' failed to provide an identifier", id);
        obj = Seeker.findSeeker(id);
        Assert.assertNotNull("Find method for 'Seeker' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySeeker(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Seeker' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SeekerIntegrationTest.testMergeUpdate() {
        Seeker obj = dod.getRandomSeeker();
        Assert.assertNotNull("Data on demand for 'Seeker' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Seeker' failed to provide an identifier", id);
        obj = Seeker.findSeeker(id);
        boolean modified =  dod.modifySeeker(obj);
        Integer currentVersion = obj.getVersion();
        Seeker merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Seeker' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SeekerIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Seeker' failed to initialize correctly", dod.getRandomSeeker());
        Seeker obj = dod.getNewTransientSeeker(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Seeker' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Seeker' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Seeker' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SeekerIntegrationTest.testRemove() {
        Seeker obj = dod.getRandomSeeker();
        Assert.assertNotNull("Data on demand for 'Seeker' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Seeker' failed to provide an identifier", id);
        obj = Seeker.findSeeker(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Seeker' with identifier '" + id + "'", Seeker.findSeeker(id));
    }
    
}
