// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jclarity.had_one_dismissal.domain;

import com.jclarity.had_one_dismissal.domain.Seeker;
import com.jclarity.had_one_dismissal.domain.SeekerDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SeekerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SeekerDataOnDemand: @Component;
    
    private Random SeekerDataOnDemand.rnd = new SecureRandom();
    
    private List<Seeker> SeekerDataOnDemand.data;
    
    public Seeker SeekerDataOnDemand.getNewTransientSeeker(int index) {
        Seeker obj = new Seeker();
        setFirstName(obj, index);
        setSurName(obj, index);
        setYearsExperience(obj, index);
        return obj;
    }
    
    public void SeekerDataOnDemand.setFirstName(Seeker obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    public void SeekerDataOnDemand.setSurName(Seeker obj, int index) {
        String surName = "surNamex_" + index;
        obj.setSurName(surName);
    }
    
    public void SeekerDataOnDemand.setYearsExperience(Seeker obj, int index) {
        int yearsExperience = index;
        obj.setYearsExperience(yearsExperience);
    }
    
    public Seeker SeekerDataOnDemand.getSpecificSeeker(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Seeker obj = data.get(index);
        Long id = obj.getId();
        return Seeker.findSeeker(id);
    }
    
    public Seeker SeekerDataOnDemand.getRandomSeeker() {
        init();
        Seeker obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Seeker.findSeeker(id);
    }
    
    public boolean SeekerDataOnDemand.modifySeeker(Seeker obj) {
        return false;
    }
    
    public void SeekerDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Seeker.findSeekerEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Seeker' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Seeker>();
        for (int i = 0; i < 10; i++) {
            Seeker obj = getNewTransientSeeker(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
