// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jclarity.had_one_dismissal.domain;

import com.jclarity.had_one_dismissal.domain.JobListing;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect JobListing_Roo_Configurable {
    
    declare @type: JobListing: @Configurable;
    
}
