// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jclarity.had_one_dismissal.domain;

import com.jclarity.had_one_dismissal.domain.Tag;

privileged aspect Tag_Roo_JavaBean {
    
    public String Tag.getName() {
        return this.name;
    }
    
    public void Tag.setName(String name) {
        this.name = name;
    }
    
}
