// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jclarity.had_one_dismissal.domain;

import com.jclarity.had_one_dismissal.domain.JobListing;
import com.jclarity.had_one_dismissal.domain.JobListingDataOnDemand;
import com.jclarity.had_one_dismissal.domain.JobListingIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JobListingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JobListingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JobListingIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JobListingIntegrationTest: @Transactional;
    
    @Autowired
    JobListingDataOnDemand JobListingIntegrationTest.dod;
    
    @Test
    public void JobListingIntegrationTest.testCountJobListings() {
        Assert.assertNotNull("Data on demand for 'JobListing' failed to initialize correctly", dod.getRandomJobListing());
        long count = JobListing.countJobListings();
        Assert.assertTrue("Counter for 'JobListing' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JobListingIntegrationTest.testFindJobListing() {
        JobListing obj = dod.getRandomJobListing();
        Assert.assertNotNull("Data on demand for 'JobListing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobListing' failed to provide an identifier", id);
        obj = JobListing.findJobListing(id);
        Assert.assertNotNull("Find method for 'JobListing' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JobListing' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JobListingIntegrationTest.testFindAllJobListings() {
        Assert.assertNotNull("Data on demand for 'JobListing' failed to initialize correctly", dod.getRandomJobListing());
        long count = JobListing.countJobListings();
        Assert.assertTrue("Too expensive to perform a find all test for 'JobListing', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JobListing> result = JobListing.findAllJobListings();
        Assert.assertNotNull("Find all method for 'JobListing' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JobListing' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JobListingIntegrationTest.testFindJobListingEntries() {
        Assert.assertNotNull("Data on demand for 'JobListing' failed to initialize correctly", dod.getRandomJobListing());
        long count = JobListing.countJobListings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JobListing> result = JobListing.findJobListingEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JobListing' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JobListing' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JobListingIntegrationTest.testFlush() {
        JobListing obj = dod.getRandomJobListing();
        Assert.assertNotNull("Data on demand for 'JobListing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobListing' failed to provide an identifier", id);
        obj = JobListing.findJobListing(id);
        Assert.assertNotNull("Find method for 'JobListing' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJobListing(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JobListing' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JobListingIntegrationTest.testMergeUpdate() {
        JobListing obj = dod.getRandomJobListing();
        Assert.assertNotNull("Data on demand for 'JobListing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobListing' failed to provide an identifier", id);
        obj = JobListing.findJobListing(id);
        boolean modified =  dod.modifyJobListing(obj);
        Integer currentVersion = obj.getVersion();
        JobListing merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JobListing' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JobListingIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JobListing' failed to initialize correctly", dod.getRandomJobListing());
        JobListing obj = dod.getNewTransientJobListing(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JobListing' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JobListing' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'JobListing' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JobListingIntegrationTest.testRemove() {
        JobListing obj = dod.getRandomJobListing();
        Assert.assertNotNull("Data on demand for 'JobListing' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JobListing' failed to provide an identifier", id);
        obj = JobListing.findJobListing(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JobListing' with identifier '" + id + "'", JobListing.findJobListing(id));
    }
    
}
