// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.jclarity.auth.domain;

import com.jclarity.auth.domain.WebUser;

privileged aspect WebUser_Roo_JavaBean {
    
    public void WebUser.setUsername(String username) {
        this.username = username;
    }
    
}
